apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: "3.1.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    createNamespace: true
  values:
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    cleanupController:
      replicas: 1
    reportsController:
      replicas: 1
    crds:
        install: true
