apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: "3.1.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 1m
  timeout: 15m0s
  values:
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    cleanupController:
      enabled: true
      rbac:
        create: true
        serviceAccount:
          create: true
    reportsController:
      enabled: true
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 30
      readinessProbe:
        initialDelaySeconds: 60
        periodSeconds: 30
      rbac:
        create: true
        serviceAccount:
          create: true
    cleanupJobs:
      admissionReports:
        enabled: false
      clusterAdmissionReports:
        enabled: false
