apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: smollm2-app
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/oyedeletemitope/smollm2-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smollm2-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/smollm2/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: smollm2-app
  targetNamespace: default