apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.10.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  timeout: 15m0s
  values:
    loki:
      enabled: true
    promtail:
      enabled: true
    grafana:
      enabled: false
      sidecar:
        datasources:
          enabled: true
