apiVersion: apps/v1
kind: Deployment
metadata:
  name: smollm2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smollm2-vllm-vllm
  template:
    metadata:
      labels:
        app: smollm2-vllm-vllm
    spec:
      containers:
      - name: vllm
        image: "jozu.ml/oyedeletemitope76/smollm2-vllm/vllm-cpu:v1.0.0"
        command: ["vllm", "serve", "--model", "/model"]
        ports:
        - containerPort: 8000
        env:
        - name: VLLM_DEVICE
          value: "cpu"
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        - name: VLLM_ENFORCE_EAGER
          value: "true"
        - name: VLLM_DISABLE_CUSTOM_ALL_REDUCE
          value: "true"
        resources:
          limits:
            memory: 1Gi      # Much smaller than TinyLlama's 3Gi
            cpu: "1"         # Single core sufficient
          requests:
            memory: 800Mi    # Minimal memory footprint
            cpu: "0.5"       # Half core request
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15  # Faster startup
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
      nodeSelector:
        kubernetes.io/arch: arm64 
---
apiVersion: v1
kind: Service
metadata:
  name: smollm2-service
  namespace: default
spec:
  selector:
    app: smollm2-vllm-vllm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP