apiVersion: apps/v1
kind: Deployment
metadata:
  name: smollm2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smollm2-vllm-vllm
  template:
    metadata:
      labels:
        app: smollm2-vllm-vllm
    spec:
      containers:
      - name: vllm
        image: "jozu.ml/oyedeletemitope76/smollm2-vllm/vllm-cpu:v1.0.0"
        command: ["python", "-m", "vllm.entrypoints.openai.api_server"]
        args: [
          "--model", "/model",
          "--host", "0.0.0.0",
          "--port", "8000",
          "--swap-space", "0",
          "--max-model-len", "512",
          "--max-num-seqs", "4",
          "--tensor-parallel-size", "1",
          "--disable-log-requests",
          "--enforce-eager"
        ]
        ports:
        - containerPort: 8000
        env:
        - name: VLLM_DEVICE
          value: "cpu"
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "fork"  # Changed from spawn to fork
        - name: VLLM_ENFORCE_EAGER
          value: "true"
        - name: VLLM_DISABLE_CUSTOM_ALL_REDUCE
          value: "true"
        - name: VLLM_CPU_SWAP_SPACE
          value: "0"
        - name: VLLM_DISABLE_DISK_CACHE
          value: "true"
        - name: VLLM_MAX_MODEL_LEN
          value: "512"
        - name: VLLM_MAX_NUM_SEQS
          value: "4"
        - name: VLLM_CPU_OMP_THREADS_BIND
          value: ""  # Remove explicit binding
        - name: OMP_NUM_THREADS
          value: "4"  # Increase to 4
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "1"
        - name: VLLM_USE_V1
          value: "0"
        - name: MKL_NUM_THREADS
          value: "4"
        - name: OPENBLAS_NUM_THREADS
          value: "4"
        - name: VLLM_CPU_EXECUTOR_ASYNC_WORKERS
          value: "1"  # Limit async workers
        - name: TORCH_THREADS
          value: "4"  # PyTorch threading
        resources:
          limits:
            memory: 2Gi      # Increased memory
            cpu: "2"         # Increased CPU limit significantly
          requests:
            memory: 1Gi      # Increased memory request
            cpu: "1"         # Increased CPU request
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 180  # Increased for slower startup
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 240   # Increased initial delay
          periodSeconds: 60
          timeoutSeconds: 20
          failureThreshold: 5
      nodeSelector:
        kubernetes.io/arch: arm64

---
apiVersion: v1
kind: Service
metadata:
  name: smollm2-service
  namespace: default
spec:
  selector:
    app: smollm2-vllm-vllm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP