apiVersion: apps/v1
kind: Deployment
metadata:
  name: smollm2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smollm2-vllm-vllm
  template:
    metadata:
      labels:
        app: smollm2-vllm-vllm
    spec:
      containers:
      - name: vllm
        image: "jozu.ml/oyedeletemitope76/smollm2-vllm/vllm-cpu:v1.0.0"
        # Use explicit command-line arguments instead of environment variables
        command: 
          - "vllm"
          - "serve"
          - "/model"
          - "--cpu-swap-space"
          - "0"
          - "--disable-custom-all-reduce"
          - "--enforce-eager"
          - "--max-model-len"
          - "1024"
          - "--device"
          - "cpu"
          - "--worker-multiproc-method"
          - "spawn"
        ports:
        - containerPort: 8000
        env:
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        resources:
          limits:
            memory: 3Gi
            cpu: "1"
          requests:
            memory: 2Gi
            cpu: "0.5"
        # Increased timeouts for model loading
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
      nodeSelector:
        kubernetes.io/arch: arm64

---
apiVersion: v1
kind: Service
metadata:
  name: smollm2-service
  namespace: default
spec:
  selector:
    app: smollm2-vllm-vllm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP