apiVersion: apps/v1
kind: Deployment
metadata:
  name: smollm2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smollm2-vllm-vllm
  template:
    metadata:
      labels:
        app: smollm2-vllm-vllm
    spec:
      containers:
      - name: vllm
        image: "jozu.ml/oyedeletemitope76/smollm2-vllm/vllm-cpu:v1.0.1"
        command: ["vllm", "serve", "/model"]
        args: [
          "--swap-space", "0",
          "--max-model-len", "512",
          "--max-num-seqs", "4",
          "--tensor-parallel-size", "1",
          "--disable-log-requests"
        ]
        ports:
        - containerPort: 8000
        env:
        # Core vLLM settings
        - name: VLLM_DEVICE
          value: "cpu"
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        - name: VLLM_ENFORCE_EAGER
          value: "true"
        - name: VLLM_DISABLE_CUSTOM_ALL_REDUCE
          value: "true"
        
        # CPU Thread Configuration - THIS IS THE KEY FIX
        - name: VLLM_CPU_OMP_THREADS_BIND
          value: "0-1"  # Bind to CPU cores 0-1 (matches our 2 CPU limit)
        - name: OMP_NUM_THREADS
          value: "2"    # Must match the number of cores in BIND
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "1"
        
        # Additional CPU optimizations
        - name: VLLM_CPU_SWAP_SPACE
          value: "0"
        - name: VLLM_DISABLE_DISK_CACHE
          value: "true"
        - name: VLLM_MAX_MODEL_LEN
          value: "512"
        - name: VLLM_MAX_NUM_SEQS
          value: "4"
        
        # Torch CPU settings
        - name: TORCH_THREADS
          value: "2"
        - name: MKL_NUM_THREADS
          value: "2"
        - name: OPENBLAS_NUM_THREADS
          value: "2"
        - name: VLLM_CPU_NUMA_NODES
          value: "1"

        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 240
          periodSeconds: 60
          timeoutSeconds: 20
          failureThreshold: 5
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: smollm2-service
  namespace: default
spec:
  selector:
    app: smollm2-vllm-vllm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP