apiVersion: apps/v1
kind: Deployment
metadata:
  name: smollm2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smollm2-vllm-vllm
  template:
    metadata:
      labels:
        app: smollm2-vllm-vllm
    spec:
      containers:
      - name: vllm
        image: "jozu.ml/oyedeletemitope76/smollm2-vllm/vllm-cpu:v1.0.0"
        command: ["vllm", "serve", "/model"]
        args: [
          "--swap-space", "0",
          "--max-model-len", "512",
          "--max-num-seqs", "4",
          "--tensor-parallel-size", "1"
        ]
        ports:
        - containerPort: 8000
        env:
        - name: VLLM_DEVICE
          value: "cpu"
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: "spawn"
        - name: VLLM_ENFORCE_EAGER
          value: "true"
        - name: VLLM_DISABLE_CUSTOM_ALL_REDUCE
          value: "true"
        - name: VLLM_CPU_SWAP_SPACE
          value: "0"
        - name: VLLM_DISABLE_DISK_CACHE
          value: "true"
        - name: VLLM_MAX_MODEL_LEN
          value: "512"
        - name: VLLM_MAX_NUM_SEQS
          value: "4"
        resources:
          limits:
            memory: 1Gi     # Much smaller for constrained environment
            cpu: "0.5"
          requests:
            memory: 512Mi   # Minimal memory request
            cpu: "0.25"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30  # Increased for model loading
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60   # Increased for initial startup
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: smollm2-service
  namespace: default
spec:
  selector:
    app: smollm2-vllm-vllm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP