apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 5m
  chart:
    spec:
      chart: trivy-operator
      version: "0.22.0"
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      interval: 1m
  timeout: 15m0s
  values:
    trivy:
      ignoreUnfixed: true
